<?php
// date_default_timezone_set('America/New_York');

function cipher_menu() {
    $items = array();
    $items['cipher_ui'] = array(
        'title' => 'Custom Shift Cipher Module',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('input_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['cipher_result_page'] = array(
        'title' => 'Check Out the Encrypted Phrase!',
        'page callback' => 'display_result',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function input_form() {
    $form['shift_value'] = array(
        '#type' => 'textfield',
        '#title' => 'Shift value',
        '#description' => 'A shift value is the number of places to shift each letter over.',
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
        '#attributes' => array(
            'placeholder' => t('Enter a number'),
        ),

    );
    $form['shift_direction'] = array(
        '#type' => 'textfield',
        '#title' => 'Shift direction',
        '#description' => 'Ex: "Right" or "Left".',
        '#element_validate' => array('element_validate_direction'),
        // http://php.net/manual/en/function.ctype-alpha.php
        '#required' => TRUE,
        '#attributes' => array(
            'placeholder' => t('Enter a shift direction'),
        ),
    );
    $form['input_phrase'] = array(
        '#type' => 'textfield',
        '#title' => 'Phrase',
        '#required' => TRUE,
        '#element_validate' => array('element_validate_phrase'),
        '#attributes' => array(
            'placeholder' => t('Enter a phrase to encrypt'),
        ),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt!',
    );

    return $form;
}

// ============================= Form Validation ============================= //

function element_validate_direction($element) {
    $input_direction = strtoupper($element['#value']);
    $valid_directions = array('RIGHT', 'LEFT');

    if (!in_array($input_direction, $valid_directions, TRUE)) {
        form_error($element, t('Direction must either be "Left" or "Right".'));
    }
}

function element_validate_phrase($element) {
    $valid = '/[[:alpha:](.|,|;|:|?|!|"|\'|\s)]+/i'; //tested on regex101.com

    if (!preg_match_all($valid, $element['#value'])) {
        form_error($element, t('The only special characters permitted are spaces and punctuation.'));
    }

    // echo '<pre>';
    // var_dump($array_of_words);
    // echo '</pre>';
    // exit;

}
