<?php

function cipher_menu() {
    $items = array();
    $items['cipher_ui'] = array(
        'title' => 'Custom Shift Cipher Module',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('input_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['cipher_result_page'] = array(
        'title' => 'Check Out the Encrypted Phrase!',
        'page callback' => 'display_result',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function input_form() {
    $form['shift_value'] = array(
        '#type' => 'textfield',
        '#title' => 'Shift value',
        '#description' => 'A shift value is the number of places to shift each letter over.',
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
        '#attributes' => array(
            'placeholder' => t('Enter a number'),
        ),

    );
    $form['shift_direction'] = array(
        '#type' => 'textfield',
        '#title' => 'Shift direction',
        '#description' => 'Example: "right" or "left".',
        '#required' => TRUE,
        '#attributes' => array(
            'placeholder' => t('Enter a shift direction'),
        ),
    );
    $form['input_phrase'] = array(
        '#type' => 'textfield',
        '#title' => 'Phrase',
        '#required' => TRUE,
        '#attributes' => array(
            'placeholder' => t('Enter a phrase to encrypt'),
        ),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt!',
    );

    return $form;
}
